name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Встановлюємо офіційний Google Cloud SDK на віртуальну машину GitHub
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # Запускаємо оригінальну команду деплою для 2nd gen
    - name: Deploy 2nd Gen Function
      run: |
        gcloud functions deploy school-bot-function \
          --gen2 \
          --runtime=python311 \
          --region=europe-west3 \
          --source=. \
          --entry-point=telegram_webhook \
          --trigger-http \
          --allow-unauthenticated \
          --memory=512MiB \
          --set-env-vars BOT_TOKEN="${{ secrets.BOT_TOKEN }}"